import json

import pytest
from fastapi.testclient import TestClient
from semantic_kernel.contents import AuthorRole, ChatMessageContent

from src.blueprint_export import export_blueprint
from src.blueprint import (
    AgentSystemBlueprint,
    build_blueprint_fallback,
    generate_blueprint,
    parse_blueprint_response,
)
from src.reporting import save_report
from src.web_server import app


def test_blueprint_schema_accepts_minimal_valid_payload():
    blueprint = AgentSystemBlueprint.model_validate(
        {
            "schema_version": 1,
            "id": "bp_test",
            "session_id": "s1",
            "name": "Security Ticket Agent",
            "status": "draft",
            "problem_statement": "Turn vulnerability notes into repair tickets.",
            "target_user": "Security engineer",
            "use_cases": ["Create a repair-ready ticket"],
            "non_goals": ["Auto-fix code"],
            "input_contract": {
                "description": "Vulnerability details",
                "examples": [],
                "required_fields": ["title"],
            },
            "output_contract": {
                "description": "Ticket markdown",
                "format": "markdown",
                "required_sections": ["summary"],
            },
            "workflow": {"steps": []},
            "agents": [],
            "tools": [],
            "evaluation": {"criteria": ["Ticket has owner and reproduction"], "test_cases": []},
            "risks": [],
            "exports": [],
            "generation": {"source": "model", "warnings": []},
        }
    )

    assert blueprint.schema_version == 1
    assert blueprint.name == "Security Ticket Agent"


def test_parse_blueprint_response_strips_think_blocks():
    payload = {
        "schema_version": 1,
        "id": "bp_test",
        "session_id": "s1",
        "name": "<think>hidden</think>Visible Blueprint",
        "status": "draft",
        "problem_statement": "Problem",
        "target_user": "User",
        "use_cases": [],
        "non_goals": [],
        "input_contract": {"description": "Input", "examples": [], "required_fields": []},
        "output_contract": {"description": "Output", "format": "markdown", "required_sections": []},
        "workflow": {"steps": []},
        "agents": [],
        "tools": [],
        "evaluation": {"criteria": [], "test_cases": []},
        "risks": [],
        "exports": [],
        "generation": {"source": "model", "warnings": []},
    }

    blueprint = parse_blueprint_response(json.dumps(payload), session_id="s1")

    assert blueprint.name == "Visible Blueprint"


def test_parse_blueprint_response_normalizes_model_shorthand_payload():
    payload = {
        "schema_version": "1.0",
        "id": "bp_model",
        "session_id": "s1",
        "name": "Model Blueprint",
        "status": "proposed",
        "problem_statement": "Problem",
        "target_user": {
            "primary": "Security engineer",
            "secondary": ["Developer lead"],
        },
        "use_cases": [
            {"id": "uc-1", "title": "Normalize input", "description": "Parse scanner output"},
        ],
        "input_contract": {
            "required": "Vulnerability data",
            "examples": [{"scanner": "nessus"}],
            "format": "JSON",
        },
        "output_contract": {
            "ticket_format": "Structured ticket",
            "fields": ["title", "severity"],
        },
        "workflow": [
            "Input Normalization: Convert raw scanner data",
            "Ticket Generation: Create draft ticket",
        ],
        "agents": [{"id": "generator", "role": "Creates tickets", "description": "Drafts ticket content"}],
        "tools": [{"name": "Ticket API", "purpose": "Create tickets"}],
        "evaluation": {"metrics": ["accuracy"], "targets": {"accuracy": ">95%"}},
        "risks": [{"title": "False positives", "severity": "critical", "mitigation": "Review queue"}],
        "exports": "implementation notes",
        "generation": "generated by model",
    }

    blueprint = parse_blueprint_response(json.dumps(payload), session_id="s1")

    assert blueprint.schema_version == 1
    assert blueprint.status == "draft"
    assert "Security engineer" in blueprint.target_user
    assert blueprint.use_cases == ["Normalize input: Parse scanner output"]
    assert blueprint.input_contract.required_fields == ["Vulnerability data"]
    assert blueprint.input_contract.examples == ['{"scanner": "nessus"}']
    assert blueprint.output_contract.required_sections == ["title", "severity"]
    assert blueprint.workflow.steps[0].id == "step_1"
    assert blueprint.workflow.steps[0].name == "Input Normalization"
    assert blueprint.agents[0].name == "generator"
    assert blueprint.agents[0].goal == "Drafts ticket content"
    assert blueprint.risks[0].risk == "False positives"
    assert blueprint.risks[0].severity == "high"
    assert blueprint.evaluation.criteria == ["accuracy"]
    assert blueprint.evaluation.test_cases == ["accuracy: >95%"]
    assert blueprint.exports == []
    assert blueprint.generation.source == "model"
    assert "generated by model" in blueprint.generation.warnings

def test_parse_blueprint_response_parses_serialized_target_user_and_criteria():
    payload = {
        "schema_version": 1,
        "id": "bp_serialized",
        "session_id": "s1",
        "name": "Serialized Blueprint",
        "status": "draft",
        "problem_statement": "Problem",
        "target_user": json.dumps([{"role": "安全工程师", "need": "生成修复工单"}], ensure_ascii=False),
        "use_cases": [],
        "non_goals": [],
        "input_contract": {"description": "Input", "examples": [], "required_fields": []},
        "output_contract": {"description": "Output", "format": "markdown", "required_sections": []},
        "workflow": {"steps": []},
        "agents": [
            {
                "name": "Generator",
                "role": "生成器",
                "goal": "生成工单",
                "instructions": "根据讨论结论生成完整工单",
            }
        ],
        "tools": [],
        "evaluation": {
            "criteria": [
                "{'name': '字段完整性', 'description': '必须包含标题、复现步骤和修复建议'}"
            ],
            "test_cases": [],
        },
        "risks": [],
        "exports": [],
        "generation": {
            "source": "model",
            "warnings": ["模型输出格式校验未通过（第1次）：JSONDecodeError: bad"]
        },
    }

    blueprint = parse_blueprint_response(json.dumps(payload, ensure_ascii=False), session_id="s1")

    assert blueprint.target_user == [{"role": "安全工程师", "need": "生成修复工单"}]
    assert blueprint.evaluation.criteria == [
        {"name": "字段完整性", "description": "必须包含标题、复现步骤和修复建议"}
    ]
    assert blueprint.workflow.steps[0].owner_agent == "Generator"
    assert blueprint.workflow.steps[0].name == "Generator 执行"
    assert blueprint.generation.warnings == []

def test_blueprint_fallback_is_exportable_and_warns():
    blueprint = build_blueprint_fallback(
        session_id="s1",
        topic="Make a security ticket agent",
        final_solution="Use a generator and reviewer.",
        dispatch_state={"selected_agents": ["Architect"]},
        warning="model output invalid",
    )

    assert blueprint.generation.source == "deterministic_fallback"
    assert "model output invalid" in blueprint.generation.warnings
    assert blueprint.agents[0].name == "Architect"


class FakeBlueprintService:
    def __init__(self, responses: list[str]):
        self.responses = responses
        self.calls: list[str] = []
        self.settings: list[object | None] = []

    async def get_chat_message_content(self, chat_history, settings=None):
        self.calls.append(chat_history.messages[-1].content or "")
        self.settings.append(settings)
        return ChatMessageContent(role=AuthorRole.ASSISTANT, content=self.responses.pop(0))


class RaisingBlueprintService:
    def __init__(self, exc: Exception):
        self.exc = exc
        self.calls = 0

    async def get_chat_message_content(self, chat_history, settings=None):
        self.calls += 1
        raise self.exc


@pytest.mark.asyncio
async def test_generate_blueprint_retries_invalid_json_then_succeeds():
    valid = {
        "schema_version": 1,
        "id": "bp_retry",
        "session_id": "s1",
        "name": "Retry Blueprint",
        "status": "draft",
        "problem_statement": "Problem",
        "target_user": "User",
        "use_cases": [],
        "non_goals": [],
        "input_contract": {"description": "Input", "examples": [], "required_fields": []},
        "output_contract": {"description": "Output", "format": "markdown", "required_sections": []},
        "workflow": {"steps": []},
        "agents": [],
        "tools": [],
        "evaluation": {"criteria": [], "test_cases": []},
        "risks": [],
        "exports": [],
        "generation": {"source": "model", "warnings": []},
    }
    service = FakeBlueprintService(["not json", json.dumps(valid)])

    result = await generate_blueprint(
        service=service,
        session_id="s1",
        topic="Idea",
        final_solution="Solution",
        dispatch_state={},
        discussion_transcript="Transcript",
    )

    assert result.blueprint.name == "Retry Blueprint"
    assert result.blueprint.generation.source == "retry"
    assert result.blueprint.generation.warnings == []
    assert "JSONDecodeError" in result.warnings[0]
    assert len(service.calls) == 2
    assert all(settings is not None for settings in service.settings)


@pytest.mark.asyncio
async def test_generate_blueprint_uses_fallback_after_two_invalid_outputs():
    service = FakeBlueprintService(["not json", "{"])

    result = await generate_blueprint(
        service=service,
        session_id="s1",
        topic="Idea",
        final_solution="Solution",
        dispatch_state={},
        discussion_transcript="Transcript",
    )

    assert result.blueprint.generation.source == "deterministic_fallback"
    assert result.warnings


@pytest.mark.asyncio
async def test_generate_blueprint_uses_fallback_when_service_raises():
    service = RaisingBlueprintService(TimeoutError("timeout"))

    result = await generate_blueprint(
        service=service,
        session_id="s1",
        topic="Idea",
        final_solution="Solution",
        dispatch_state={},
        discussion_transcript="Transcript",
    )

    assert result.blueprint.generation.source == "deterministic_fallback"
    assert result.warnings
    assert "TimeoutError" in result.warnings[0]


def _sample_blueprint() -> AgentSystemBlueprint:
    return build_blueprint_fallback(
        session_id="s1",
        topic="Make a ticket agent",
        final_solution="Use generator and reviewer.",
        dispatch_state={"selected_agents": ["Generator", "Reviewer"]},
        warning="fallback",
    )


def test_export_blueprint_json_is_parseable():
    result = export_blueprint(_sample_blueprint(), "json")

    assert result.files[0].filename.endswith(".json")
    parsed = json.loads(result.files[0].content)
    assert parsed["schema_version"] == 1


def test_export_blueprint_markdown_contains_agents_and_workflow():
    result = export_blueprint(_sample_blueprint(), "markdown")

    assert "## Agents" in result.files[0].content
    assert "## Workflow" in result.files[0].content


def test_export_blueprint_prompt_pack_has_one_file_per_agent():
    result = export_blueprint(_sample_blueprint(), "prompt_pack")

    assert {file.filename for file in result.files} == {"Generator.md", "Reviewer.md"}

def test_export_blueprint_prompt_pack_marks_short_instructions_and_adds_context():
    blueprint = AgentSystemBlueprint.model_validate(
        {
            "schema_version": 1,
            "id": "bp_prompt",
            "session_id": "s1",
            "name": "Prompt Pack Blueprint",
            "status": "draft",
            "problem_statement": "Problem",
            "target_user": "User",
            "use_cases": [],
            "non_goals": [],
            "input_contract": {"description": "Input", "examples": [], "required_fields": []},
            "output_contract": {
                "description": "Output",
                "format": "markdown",
                "required_sections": ["summary"],
            },
            "workflow": {"steps": []},
            "agents": [
                {
                    "name": "Generator",
                    "role": "生成器",
                    "goal": "生成工单",
                    "instructions": "生成工单",
                    "outputs": ["结构化工单"],
                    "collaboration_rules": ["完成后交给 Reviewer 复核"],
                }
            ],
            "tools": [],
            "evaluation": {"criteria": [], "test_cases": []},
            "risks": [],
            "exports": [],
            "generation": {"source": "model", "warnings": []},
        }
    )

    result = export_blueprint(blueprint, "prompt_pack")

    assert "agents[Generator].instructions" in result.unsupported_fields
    assert "## Expected Outputs" in result.files[0].content
    assert "结构化工单" in result.files[0].content
    assert "完成后交给 Reviewer 复核" in result.files[0].content

def test_report_includes_agent_system_blueprint(tmp_path):
    blueprint = build_blueprint_fallback(
        session_id="s1",
        topic="原议题",
        final_solution="最终方案",
        dispatch_state={"selected_agents": ["Architect"]},
        warning="test",
    )

    report_path = save_report(
        topic="原议题",
        discussion_summary="最终方案",
        discussion_transcript="讨论记录",
        voting_result=None,
        dispatch_state=None,
        blueprint=blueprint,
        output_dir=tmp_path,
    )

    content = report_path.read_text(encoding="utf-8")
    assert "## 本次讨论总览" in content
    assert "### Agents" in content
    assert "### Workflow" in content


def test_blueprint_export_endpoint_returns_files():
    client = TestClient(app)
    blueprint = _sample_blueprint().model_dump(mode="json")

    response = client.post("/api/blueprint/export", json={"format": "json", "blueprint": blueprint})

    assert response.status_code == 200
    data = response.json()
    assert data["files"][0]["filename"].endswith(".json")
